# Generated by Django 5.1.5 on 2025-01-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
