# Generated by Django 5.1.5 on 2025-01-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_carga_horario_curso_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.PositiveIntegerField(default=1, max_length=100, unique=True),
        ),
    ]
